deployment:
  tasks:
    - export DEPLOYPATH=/home/eins1367/public_html/api.freshwaterfishindonesia.com/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /bin/php artisan storage:link
    - /bin/php artisan migrate:fresh
