deployment:
  tasks:
    - export DEPLOYPATH=/home/fres2238/public_html/api.freshwaterfishindonesia.com/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /bin/ln -s ./storage/app/public public/storage
